"""empty message

Revision ID: 3bf24e4c27c3
Revises: c6cf9d49ba6d
Create Date: 2023-01-14 14:28:17.864553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bf24e4c27c3'
down_revision = 'c6cf9d49ba6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_user_post',
    sa.Column('like_id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('post_id', postgresql.UUID(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.add_column('user_post', sa.Column('like_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_post', 'like_user_post', ['like_id'], ['like_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.drop_column('user_post', 'like_id')
    op.drop_table('like_user_post')
    # ### end Alembic commands ###
